/* =================================================================================================
   🧪 SEEING V8 BYTECODE IN PRACTICE
   =================================================================================================

Let's take a simple function:

function add(a, b) {
  return a + b;
}

add(10, 20);


We can ask Node.js (which uses V8) to show us the bytecode generated
for the JavaScript code.


💻 Run:

node --print-bytecode index.js


This prints the bytecode generated by V8.


🎯 If we only want to inspect the `add` function:

node --print-bytecode --print-bytecode-filter=add index.js


This is useful because instead of seeing bytecode for everything in the
file, we can focus on the function we're studying.


/* ================================================================================================
   🔍 WHAT ARE WE LOOKING AT?
   ================================================================================================

The output will contain V8/Ignition bytecode instructions.

You may see instructions such as:

📦 Lda...
→ Load a value into the accumulator.

📦 Add...
→ Perform an addition operation.

📦 Return
→ Return the value currently held by the accumulator.

📦 Star...
→ Store the accumulator into a virtual register.

The exact instruction names and output can vary depending on the V8
version.


💡 This is where our previous concepts become REAL:

🌳 AST
   ↓
📦 Bytecode
   ↓
🔥 Ignition
   ↓
🧮 Accumulator + Virtual Registers
   ↓
⚙️ Execution


/* ================================================================================================
   ⚠️ IMPORTANT — ENGINE IMPLEMENTATIONS DIFFER
   ================================================================================================

The JavaScript language specification defines the behavior of JavaScript,
but it does NOT require every engine to implement it internally in the
same way.

Different engines have different internal architectures.

For example:

🌐 Chrome / Node.js / Edge
→ V8

🦊 Firefox
→ SpiderMonkey

🧭 Safari
→ JavaScriptCore (JSC)


Therefore:

❌ Don't expect the same bytecode.
❌ Don't expect the same interpreter architecture.
❌ Don't expect the same optimization pipeline.

Even within the SAME engine, implementation details can change between
versions.


🎯 INTERVIEW NOTE:

> "Is JavaScript bytecode the same across all browsers?"

❌ No.

Bytecode is an implementation detail of a particular engine.

The ECMAScript specification defines JavaScript's behavior, but engines
are free to implement that behavior using different internal techniques.


/* ================================================================================================
   🧠 BIG PICTURE
   ================================================================================================

JavaScript Specification
        │
        │ defines behavior
        ▼
   Different Engines
        │
   ┌────┼───────────────┐
   ▼    ▼               ▼
  V8  SpiderMonkey     JSC
   │    │               │
   ▼    ▼               ▼
Different internal representations,
bytecode formats, interpreters,
and optimization pipelines.


💡 So when we're studying:

🔥 Ignition
📜 V8 Bytecode
🧮 Accumulator
🧮 Virtual Registers

we are specifically learning about:

👉 V8's implementation.

These concepts should NOT be treated as universal requirements of
JavaScript itself.
*/
