// a question: AST is produced by the JavaScript engine parser (like Chrome V8), not Webpack or any external tool,
// and parts of it can be observed indirectly in DevTools when tracing execution.

// Addtional Explanation: 🍎

/*
🎤 Interview Question

Q: Is the AST generated by Webpack?

A:
Not necessarily.

AST (Abstract Syntax Tree) is a general concept in programming languages.

Whenever a parser reads source code, it can generate an AST.

-------------------------------------------------

In the Browser 🌐

JavaScript engines such as:

- V8 (Chrome)
- SpiderMonkey (Firefox)
- JavaScriptCore (Safari)

perform roughly:

Source Code
     ↓
Lexical Analysis (Tokenization)
     ↓
Parsing
     ↓
AST 🌳
     ↓
Bytecode / Machine Code
     ↓
Execution

So yes, the browser engine itself generates an AST internally
before executing JavaScript.

-------------------------------------------------

In Webpack 📦

Webpack also parses your files and generates ASTs.

Why?

Not to execute the code like the browser does,
but to analyze it.

Webpack uses the AST to:

✅ Detect imports and exports
✅ Build the Dependency Graph
✅ Perform Tree Shaking
✅ Remove Dead Code
✅ Minify Code
✅ Apply Transformations

-------------------------------------------------

Can We See The AST? 🔍

Yes.

Although the browser's internal AST is not directly shown in DevTools,
you can generate and inspect ASTs using tools such as:

- AST Explorer (most popular)
- Babel Parser
- Acorn
- Esprima

Example:

const userName = "Ahmed";

becomes a tree describing:

🌳 VariableDeclaration
   └── VariableDeclarator
       ├── Identifier (userName)
       └── Literal ("Ahmed")

-------------------------------------------------

Important Distinction ⚠️

Browser AST:
Purpose ➜ Execute code.

Webpack AST:
Purpose ➜ Analyze and optimize code before shipping it.

Same concept 🌳
Different goals 🎯
*/
